set -g default-terminal screen-256color
set -g terminal-overrides ",alacritty:Tc"
setw -g mouse on
setw -g mode-keys vi

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Pane navigation shortcuts
bind-key ; split-window -h -c "#{pane_current_path}"
bind-key v split-window -v -c "#{pane_current_path}"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
